// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GasPayingsColumns holds the columns for the "gas_payings" table.
	GasPayingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "order_id", Type: field.TypeUUID},
		{Name: "account_id", Type: field.TypeUUID},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"wait", "done", "canceled", "timeout"}},
		{Name: "chain_transaction_id", Type: field.TypeString},
		{Name: "platform_transaction_id", Type: field.TypeUUID},
		{Name: "duration_minutes", Type: field.TypeUint32},
		{Name: "used", Type: field.TypeBool},
		{Name: "create_at", Type: field.TypeUint32},
		{Name: "update_at", Type: field.TypeUint32},
		{Name: "delete_at", Type: field.TypeUint32},
	}
	// GasPayingsTable holds the schema information for the "gas_payings" table.
	GasPayingsTable = &schema.Table{
		Name:       "gas_payings",
		Columns:    GasPayingsColumns,
		PrimaryKey: []*schema.Column{GasPayingsColumns[0]},
	}
	// GoodPayingsColumns holds the columns for the "good_payings" table.
	GoodPayingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "order_id", Type: field.TypeUUID},
		{Name: "account_id", Type: field.TypeUUID},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"wait", "done", "canceled", "timeout"}},
		{Name: "chain_transaction_id", Type: field.TypeString},
		{Name: "platform_transaction_id", Type: field.TypeUUID},
		{Name: "create_at", Type: field.TypeUint32},
		{Name: "update_at", Type: field.TypeUint32},
		{Name: "delete_at", Type: field.TypeUint32},
	}
	// GoodPayingsTable holds the schema information for the "good_payings" table.
	GoodPayingsTable = &schema.Table{
		Name:       "good_payings",
		Columns:    GoodPayingsColumns,
		PrimaryKey: []*schema.Column{GoodPayingsColumns[0]},
	}
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "good_id", Type: field.TypeUUID},
		{Name: "app_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "units", Type: field.TypeUint32},
		{Name: "discount", Type: field.TypeUint32, Default: 0},
		{Name: "special_reduction_amount", Type: field.TypeUint64, Default: 0},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"created", "paying", "paid", "timeout", "canceled"}},
		{Name: "good_pay_id", Type: field.TypeUUID},
		{Name: "start", Type: field.TypeUint32},
		{Name: "end", Type: field.TypeUint32},
		{Name: "compensate_minutes", Type: field.TypeUint32, Default: 0},
		{Name: "compensate_elapsed_minutes", Type: field.TypeUint32, Default: 0},
		{Name: "gas_start", Type: field.TypeUint32},
		{Name: "gas_end", Type: field.TypeUint32},
		{Name: "gas_pay_ids", Type: field.TypeJSON},
		{Name: "coupon_id", Type: field.TypeUUID},
		{Name: "create_at", Type: field.TypeUint32},
		{Name: "update_at", Type: field.TypeUint32},
		{Name: "delete_at", Type: field.TypeUint32},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GasPayingsTable,
		GoodPayingsTable,
		OrdersTable,
	}
)

func init() {
}
