// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-order/pkg/db/ent/canceledorder"
	"github.com/google/uuid"
)

// CanceledOrderCreate is the builder for creating a CanceledOrder entity.
type CanceledOrderCreate struct {
	config
	mutation *CanceledOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderID sets the "order_id" field.
func (coc *CanceledOrderCreate) SetOrderID(u uuid.UUID) *CanceledOrderCreate {
	coc.mutation.SetOrderID(u)
	return coc
}

// SetCreateAt sets the "create_at" field.
func (coc *CanceledOrderCreate) SetCreateAt(u uint32) *CanceledOrderCreate {
	coc.mutation.SetCreateAt(u)
	return coc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (coc *CanceledOrderCreate) SetNillableCreateAt(u *uint32) *CanceledOrderCreate {
	if u != nil {
		coc.SetCreateAt(*u)
	}
	return coc
}

// SetUpdateAt sets the "update_at" field.
func (coc *CanceledOrderCreate) SetUpdateAt(u uint32) *CanceledOrderCreate {
	coc.mutation.SetUpdateAt(u)
	return coc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (coc *CanceledOrderCreate) SetNillableUpdateAt(u *uint32) *CanceledOrderCreate {
	if u != nil {
		coc.SetUpdateAt(*u)
	}
	return coc
}

// SetDeleteAt sets the "delete_at" field.
func (coc *CanceledOrderCreate) SetDeleteAt(u uint32) *CanceledOrderCreate {
	coc.mutation.SetDeleteAt(u)
	return coc
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (coc *CanceledOrderCreate) SetNillableDeleteAt(u *uint32) *CanceledOrderCreate {
	if u != nil {
		coc.SetDeleteAt(*u)
	}
	return coc
}

// SetID sets the "id" field.
func (coc *CanceledOrderCreate) SetID(u uuid.UUID) *CanceledOrderCreate {
	coc.mutation.SetID(u)
	return coc
}

// Mutation returns the CanceledOrderMutation object of the builder.
func (coc *CanceledOrderCreate) Mutation() *CanceledOrderMutation {
	return coc.mutation
}

// Save creates the CanceledOrder in the database.
func (coc *CanceledOrderCreate) Save(ctx context.Context) (*CanceledOrder, error) {
	var (
		err  error
		node *CanceledOrder
	)
	coc.defaults()
	if len(coc.hooks) == 0 {
		if err = coc.check(); err != nil {
			return nil, err
		}
		node, err = coc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CanceledOrderMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = coc.check(); err != nil {
				return nil, err
			}
			coc.mutation = mutation
			if node, err = coc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(coc.hooks) - 1; i >= 0; i-- {
			if coc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = coc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, coc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (coc *CanceledOrderCreate) SaveX(ctx context.Context) *CanceledOrder {
	v, err := coc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (coc *CanceledOrderCreate) Exec(ctx context.Context) error {
	_, err := coc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (coc *CanceledOrderCreate) ExecX(ctx context.Context) {
	if err := coc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (coc *CanceledOrderCreate) defaults() {
	if _, ok := coc.mutation.CreateAt(); !ok {
		v := canceledorder.DefaultCreateAt()
		coc.mutation.SetCreateAt(v)
	}
	if _, ok := coc.mutation.UpdateAt(); !ok {
		v := canceledorder.DefaultUpdateAt()
		coc.mutation.SetUpdateAt(v)
	}
	if _, ok := coc.mutation.DeleteAt(); !ok {
		v := canceledorder.DefaultDeleteAt()
		coc.mutation.SetDeleteAt(v)
	}
	if _, ok := coc.mutation.ID(); !ok {
		v := canceledorder.DefaultID()
		coc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (coc *CanceledOrderCreate) check() error {
	if _, ok := coc.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "order_id"`)}
	}
	if _, ok := coc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "create_at"`)}
	}
	if _, ok := coc.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "update_at"`)}
	}
	if _, ok := coc.mutation.DeleteAt(); !ok {
		return &ValidationError{Name: "delete_at", err: errors.New(`ent: missing required field "delete_at"`)}
	}
	return nil
}

func (coc *CanceledOrderCreate) sqlSave(ctx context.Context) (*CanceledOrder, error) {
	_node, _spec := coc.createSpec()
	if err := sqlgraph.CreateNode(ctx, coc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(uuid.UUID)
	}
	return _node, nil
}

func (coc *CanceledOrderCreate) createSpec() (*CanceledOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &CanceledOrder{config: coc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: canceledorder.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: canceledorder.FieldID,
			},
		}
	)
	_spec.OnConflict = coc.conflict
	if id, ok := coc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := coc.mutation.OrderID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: canceledorder.FieldOrderID,
		})
		_node.OrderID = value
	}
	if value, ok := coc.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: canceledorder.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := coc.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: canceledorder.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	if value, ok := coc.mutation.DeleteAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: canceledorder.FieldDeleteAt,
		})
		_node.DeleteAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CanceledOrder.Create().
//		SetOrderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CanceledOrderUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
//
func (coc *CanceledOrderCreate) OnConflict(opts ...sql.ConflictOption) *CanceledOrderUpsertOne {
	coc.conflict = opts
	return &CanceledOrderUpsertOne{
		create: coc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CanceledOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (coc *CanceledOrderCreate) OnConflictColumns(columns ...string) *CanceledOrderUpsertOne {
	coc.conflict = append(coc.conflict, sql.ConflictColumns(columns...))
	return &CanceledOrderUpsertOne{
		create: coc,
	}
}

type (
	// CanceledOrderUpsertOne is the builder for "upsert"-ing
	//  one CanceledOrder node.
	CanceledOrderUpsertOne struct {
		create *CanceledOrderCreate
	}

	// CanceledOrderUpsert is the "OnConflict" setter.
	CanceledOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderID sets the "order_id" field.
func (u *CanceledOrderUpsert) SetOrderID(v uuid.UUID) *CanceledOrderUpsert {
	u.Set(canceledorder.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *CanceledOrderUpsert) UpdateOrderID() *CanceledOrderUpsert {
	u.SetExcluded(canceledorder.FieldOrderID)
	return u
}

// SetCreateAt sets the "create_at" field.
func (u *CanceledOrderUpsert) SetCreateAt(v uint32) *CanceledOrderUpsert {
	u.Set(canceledorder.FieldCreateAt, v)
	return u
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *CanceledOrderUpsert) UpdateCreateAt() *CanceledOrderUpsert {
	u.SetExcluded(canceledorder.FieldCreateAt)
	return u
}

// SetUpdateAt sets the "update_at" field.
func (u *CanceledOrderUpsert) SetUpdateAt(v uint32) *CanceledOrderUpsert {
	u.Set(canceledorder.FieldUpdateAt, v)
	return u
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *CanceledOrderUpsert) UpdateUpdateAt() *CanceledOrderUpsert {
	u.SetExcluded(canceledorder.FieldUpdateAt)
	return u
}

// SetDeleteAt sets the "delete_at" field.
func (u *CanceledOrderUpsert) SetDeleteAt(v uint32) *CanceledOrderUpsert {
	u.Set(canceledorder.FieldDeleteAt, v)
	return u
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *CanceledOrderUpsert) UpdateDeleteAt() *CanceledOrderUpsert {
	u.SetExcluded(canceledorder.FieldDeleteAt)
	return u
}

// UpdateNewValues updates the fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CanceledOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(canceledorder.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CanceledOrderUpsertOne) UpdateNewValues() *CanceledOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(canceledorder.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.CanceledOrder.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *CanceledOrderUpsertOne) Ignore() *CanceledOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CanceledOrderUpsertOne) DoNothing() *CanceledOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CanceledOrderCreate.OnConflict
// documentation for more info.
func (u *CanceledOrderUpsertOne) Update(set func(*CanceledOrderUpsert)) *CanceledOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CanceledOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *CanceledOrderUpsertOne) SetOrderID(v uuid.UUID) *CanceledOrderUpsertOne {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *CanceledOrderUpsertOne) UpdateOrderID() *CanceledOrderUpsertOne {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.UpdateOrderID()
	})
}

// SetCreateAt sets the "create_at" field.
func (u *CanceledOrderUpsertOne) SetCreateAt(v uint32) *CanceledOrderUpsertOne {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.SetCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *CanceledOrderUpsertOne) UpdateCreateAt() *CanceledOrderUpsertOne {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *CanceledOrderUpsertOne) SetUpdateAt(v uint32) *CanceledOrderUpsertOne {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.SetUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *CanceledOrderUpsertOne) UpdateUpdateAt() *CanceledOrderUpsertOne {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.UpdateUpdateAt()
	})
}

// SetDeleteAt sets the "delete_at" field.
func (u *CanceledOrderUpsertOne) SetDeleteAt(v uint32) *CanceledOrderUpsertOne {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.SetDeleteAt(v)
	})
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *CanceledOrderUpsertOne) UpdateDeleteAt() *CanceledOrderUpsertOne {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.UpdateDeleteAt()
	})
}

// Exec executes the query.
func (u *CanceledOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CanceledOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CanceledOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CanceledOrderUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CanceledOrderUpsertOne.ID is not supported by MySQL driver. Use CanceledOrderUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CanceledOrderUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CanceledOrderCreateBulk is the builder for creating many CanceledOrder entities in bulk.
type CanceledOrderCreateBulk struct {
	config
	builders []*CanceledOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the CanceledOrder entities in the database.
func (cocb *CanceledOrderCreateBulk) Save(ctx context.Context) ([]*CanceledOrder, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cocb.builders))
	nodes := make([]*CanceledOrder, len(cocb.builders))
	mutators := make([]Mutator, len(cocb.builders))
	for i := range cocb.builders {
		func(i int, root context.Context) {
			builder := cocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CanceledOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cocb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cocb *CanceledOrderCreateBulk) SaveX(ctx context.Context) []*CanceledOrder {
	v, err := cocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cocb *CanceledOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := cocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cocb *CanceledOrderCreateBulk) ExecX(ctx context.Context) {
	if err := cocb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CanceledOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CanceledOrderUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
//
func (cocb *CanceledOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *CanceledOrderUpsertBulk {
	cocb.conflict = opts
	return &CanceledOrderUpsertBulk{
		create: cocb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CanceledOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cocb *CanceledOrderCreateBulk) OnConflictColumns(columns ...string) *CanceledOrderUpsertBulk {
	cocb.conflict = append(cocb.conflict, sql.ConflictColumns(columns...))
	return &CanceledOrderUpsertBulk{
		create: cocb,
	}
}

// CanceledOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of CanceledOrder nodes.
type CanceledOrderUpsertBulk struct {
	create *CanceledOrderCreateBulk
}

// UpdateNewValues updates the fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CanceledOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(canceledorder.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CanceledOrderUpsertBulk) UpdateNewValues() *CanceledOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(canceledorder.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CanceledOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *CanceledOrderUpsertBulk) Ignore() *CanceledOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CanceledOrderUpsertBulk) DoNothing() *CanceledOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CanceledOrderCreateBulk.OnConflict
// documentation for more info.
func (u *CanceledOrderUpsertBulk) Update(set func(*CanceledOrderUpsert)) *CanceledOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CanceledOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *CanceledOrderUpsertBulk) SetOrderID(v uuid.UUID) *CanceledOrderUpsertBulk {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *CanceledOrderUpsertBulk) UpdateOrderID() *CanceledOrderUpsertBulk {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.UpdateOrderID()
	})
}

// SetCreateAt sets the "create_at" field.
func (u *CanceledOrderUpsertBulk) SetCreateAt(v uint32) *CanceledOrderUpsertBulk {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.SetCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *CanceledOrderUpsertBulk) UpdateCreateAt() *CanceledOrderUpsertBulk {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *CanceledOrderUpsertBulk) SetUpdateAt(v uint32) *CanceledOrderUpsertBulk {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.SetUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *CanceledOrderUpsertBulk) UpdateUpdateAt() *CanceledOrderUpsertBulk {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.UpdateUpdateAt()
	})
}

// SetDeleteAt sets the "delete_at" field.
func (u *CanceledOrderUpsertBulk) SetDeleteAt(v uint32) *CanceledOrderUpsertBulk {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.SetDeleteAt(v)
	})
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *CanceledOrderUpsertBulk) UpdateDeleteAt() *CanceledOrderUpsertBulk {
	return u.Update(func(s *CanceledOrderUpsert) {
		s.UpdateDeleteAt()
	})
}

// Exec executes the query.
func (u *CanceledOrderUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CanceledOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CanceledOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CanceledOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
