// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-order/pkg/db/ent/gaspaying"
	"github.com/google/uuid"
)

// GasPayingCreate is the builder for creating a GasPaying entity.
type GasPayingCreate struct {
	config
	mutation *GasPayingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderID sets the "order_id" field.
func (gpc *GasPayingCreate) SetOrderID(u uuid.UUID) *GasPayingCreate {
	gpc.mutation.SetOrderID(u)
	return gpc
}

// SetPaymentID sets the "payment_id" field.
func (gpc *GasPayingCreate) SetPaymentID(u uuid.UUID) *GasPayingCreate {
	gpc.mutation.SetPaymentID(u)
	return gpc
}

// SetDurationMinutes sets the "duration_minutes" field.
func (gpc *GasPayingCreate) SetDurationMinutes(u uint32) *GasPayingCreate {
	gpc.mutation.SetDurationMinutes(u)
	return gpc
}

// SetCreateAt sets the "create_at" field.
func (gpc *GasPayingCreate) SetCreateAt(u uint32) *GasPayingCreate {
	gpc.mutation.SetCreateAt(u)
	return gpc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (gpc *GasPayingCreate) SetNillableCreateAt(u *uint32) *GasPayingCreate {
	if u != nil {
		gpc.SetCreateAt(*u)
	}
	return gpc
}

// SetUpdateAt sets the "update_at" field.
func (gpc *GasPayingCreate) SetUpdateAt(u uint32) *GasPayingCreate {
	gpc.mutation.SetUpdateAt(u)
	return gpc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (gpc *GasPayingCreate) SetNillableUpdateAt(u *uint32) *GasPayingCreate {
	if u != nil {
		gpc.SetUpdateAt(*u)
	}
	return gpc
}

// SetDeleteAt sets the "delete_at" field.
func (gpc *GasPayingCreate) SetDeleteAt(u uint32) *GasPayingCreate {
	gpc.mutation.SetDeleteAt(u)
	return gpc
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (gpc *GasPayingCreate) SetNillableDeleteAt(u *uint32) *GasPayingCreate {
	if u != nil {
		gpc.SetDeleteAt(*u)
	}
	return gpc
}

// SetID sets the "id" field.
func (gpc *GasPayingCreate) SetID(u uuid.UUID) *GasPayingCreate {
	gpc.mutation.SetID(u)
	return gpc
}

// Mutation returns the GasPayingMutation object of the builder.
func (gpc *GasPayingCreate) Mutation() *GasPayingMutation {
	return gpc.mutation
}

// Save creates the GasPaying in the database.
func (gpc *GasPayingCreate) Save(ctx context.Context) (*GasPaying, error) {
	var (
		err  error
		node *GasPaying
	)
	gpc.defaults()
	if len(gpc.hooks) == 0 {
		if err = gpc.check(); err != nil {
			return nil, err
		}
		node, err = gpc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GasPayingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = gpc.check(); err != nil {
				return nil, err
			}
			gpc.mutation = mutation
			if node, err = gpc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(gpc.hooks) - 1; i >= 0; i-- {
			if gpc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gpc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gpc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gpc *GasPayingCreate) SaveX(ctx context.Context) *GasPaying {
	v, err := gpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gpc *GasPayingCreate) Exec(ctx context.Context) error {
	_, err := gpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gpc *GasPayingCreate) ExecX(ctx context.Context) {
	if err := gpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gpc *GasPayingCreate) defaults() {
	if _, ok := gpc.mutation.CreateAt(); !ok {
		v := gaspaying.DefaultCreateAt()
		gpc.mutation.SetCreateAt(v)
	}
	if _, ok := gpc.mutation.UpdateAt(); !ok {
		v := gaspaying.DefaultUpdateAt()
		gpc.mutation.SetUpdateAt(v)
	}
	if _, ok := gpc.mutation.DeleteAt(); !ok {
		v := gaspaying.DefaultDeleteAt()
		gpc.mutation.SetDeleteAt(v)
	}
	if _, ok := gpc.mutation.ID(); !ok {
		v := gaspaying.DefaultID()
		gpc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gpc *GasPayingCreate) check() error {
	if _, ok := gpc.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "order_id"`)}
	}
	if _, ok := gpc.mutation.PaymentID(); !ok {
		return &ValidationError{Name: "payment_id", err: errors.New(`ent: missing required field "payment_id"`)}
	}
	if _, ok := gpc.mutation.DurationMinutes(); !ok {
		return &ValidationError{Name: "duration_minutes", err: errors.New(`ent: missing required field "duration_minutes"`)}
	}
	if _, ok := gpc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "create_at"`)}
	}
	if _, ok := gpc.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "update_at"`)}
	}
	if _, ok := gpc.mutation.DeleteAt(); !ok {
		return &ValidationError{Name: "delete_at", err: errors.New(`ent: missing required field "delete_at"`)}
	}
	return nil
}

func (gpc *GasPayingCreate) sqlSave(ctx context.Context) (*GasPaying, error) {
	_node, _spec := gpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(uuid.UUID)
	}
	return _node, nil
}

func (gpc *GasPayingCreate) createSpec() (*GasPaying, *sqlgraph.CreateSpec) {
	var (
		_node = &GasPaying{config: gpc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: gaspaying.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: gaspaying.FieldID,
			},
		}
	)
	_spec.OnConflict = gpc.conflict
	if id, ok := gpc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := gpc.mutation.OrderID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: gaspaying.FieldOrderID,
		})
		_node.OrderID = value
	}
	if value, ok := gpc.mutation.PaymentID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: gaspaying.FieldPaymentID,
		})
		_node.PaymentID = value
	}
	if value, ok := gpc.mutation.DurationMinutes(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: gaspaying.FieldDurationMinutes,
		})
		_node.DurationMinutes = value
	}
	if value, ok := gpc.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: gaspaying.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := gpc.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: gaspaying.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	if value, ok := gpc.mutation.DeleteAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: gaspaying.FieldDeleteAt,
		})
		_node.DeleteAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GasPaying.Create().
//		SetOrderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GasPayingUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
//
func (gpc *GasPayingCreate) OnConflict(opts ...sql.ConflictOption) *GasPayingUpsertOne {
	gpc.conflict = opts
	return &GasPayingUpsertOne{
		create: gpc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GasPaying.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (gpc *GasPayingCreate) OnConflictColumns(columns ...string) *GasPayingUpsertOne {
	gpc.conflict = append(gpc.conflict, sql.ConflictColumns(columns...))
	return &GasPayingUpsertOne{
		create: gpc,
	}
}

type (
	// GasPayingUpsertOne is the builder for "upsert"-ing
	//  one GasPaying node.
	GasPayingUpsertOne struct {
		create *GasPayingCreate
	}

	// GasPayingUpsert is the "OnConflict" setter.
	GasPayingUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderID sets the "order_id" field.
func (u *GasPayingUpsert) SetOrderID(v uuid.UUID) *GasPayingUpsert {
	u.Set(gaspaying.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *GasPayingUpsert) UpdateOrderID() *GasPayingUpsert {
	u.SetExcluded(gaspaying.FieldOrderID)
	return u
}

// SetPaymentID sets the "payment_id" field.
func (u *GasPayingUpsert) SetPaymentID(v uuid.UUID) *GasPayingUpsert {
	u.Set(gaspaying.FieldPaymentID, v)
	return u
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *GasPayingUpsert) UpdatePaymentID() *GasPayingUpsert {
	u.SetExcluded(gaspaying.FieldPaymentID)
	return u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (u *GasPayingUpsert) SetDurationMinutes(v uint32) *GasPayingUpsert {
	u.Set(gaspaying.FieldDurationMinutes, v)
	return u
}

// UpdateDurationMinutes sets the "duration_minutes" field to the value that was provided on create.
func (u *GasPayingUpsert) UpdateDurationMinutes() *GasPayingUpsert {
	u.SetExcluded(gaspaying.FieldDurationMinutes)
	return u
}

// SetCreateAt sets the "create_at" field.
func (u *GasPayingUpsert) SetCreateAt(v uint32) *GasPayingUpsert {
	u.Set(gaspaying.FieldCreateAt, v)
	return u
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *GasPayingUpsert) UpdateCreateAt() *GasPayingUpsert {
	u.SetExcluded(gaspaying.FieldCreateAt)
	return u
}

// SetUpdateAt sets the "update_at" field.
func (u *GasPayingUpsert) SetUpdateAt(v uint32) *GasPayingUpsert {
	u.Set(gaspaying.FieldUpdateAt, v)
	return u
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *GasPayingUpsert) UpdateUpdateAt() *GasPayingUpsert {
	u.SetExcluded(gaspaying.FieldUpdateAt)
	return u
}

// SetDeleteAt sets the "delete_at" field.
func (u *GasPayingUpsert) SetDeleteAt(v uint32) *GasPayingUpsert {
	u.Set(gaspaying.FieldDeleteAt, v)
	return u
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *GasPayingUpsert) UpdateDeleteAt() *GasPayingUpsert {
	u.SetExcluded(gaspaying.FieldDeleteAt)
	return u
}

// UpdateNewValues updates the fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GasPaying.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(gaspaying.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *GasPayingUpsertOne) UpdateNewValues() *GasPayingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(gaspaying.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.GasPaying.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *GasPayingUpsertOne) Ignore() *GasPayingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GasPayingUpsertOne) DoNothing() *GasPayingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GasPayingCreate.OnConflict
// documentation for more info.
func (u *GasPayingUpsertOne) Update(set func(*GasPayingUpsert)) *GasPayingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GasPayingUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *GasPayingUpsertOne) SetOrderID(v uuid.UUID) *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *GasPayingUpsertOne) UpdateOrderID() *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdateOrderID()
	})
}

// SetPaymentID sets the "payment_id" field.
func (u *GasPayingUpsertOne) SetPaymentID(v uuid.UUID) *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetPaymentID(v)
	})
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *GasPayingUpsertOne) UpdatePaymentID() *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdatePaymentID()
	})
}

// SetDurationMinutes sets the "duration_minutes" field.
func (u *GasPayingUpsertOne) SetDurationMinutes(v uint32) *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetDurationMinutes(v)
	})
}

// UpdateDurationMinutes sets the "duration_minutes" field to the value that was provided on create.
func (u *GasPayingUpsertOne) UpdateDurationMinutes() *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdateDurationMinutes()
	})
}

// SetCreateAt sets the "create_at" field.
func (u *GasPayingUpsertOne) SetCreateAt(v uint32) *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *GasPayingUpsertOne) UpdateCreateAt() *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *GasPayingUpsertOne) SetUpdateAt(v uint32) *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *GasPayingUpsertOne) UpdateUpdateAt() *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdateUpdateAt()
	})
}

// SetDeleteAt sets the "delete_at" field.
func (u *GasPayingUpsertOne) SetDeleteAt(v uint32) *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetDeleteAt(v)
	})
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *GasPayingUpsertOne) UpdateDeleteAt() *GasPayingUpsertOne {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdateDeleteAt()
	})
}

// Exec executes the query.
func (u *GasPayingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GasPayingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GasPayingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GasPayingUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: GasPayingUpsertOne.ID is not supported by MySQL driver. Use GasPayingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GasPayingUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GasPayingCreateBulk is the builder for creating many GasPaying entities in bulk.
type GasPayingCreateBulk struct {
	config
	builders []*GasPayingCreate
	conflict []sql.ConflictOption
}

// Save creates the GasPaying entities in the database.
func (gpcb *GasPayingCreateBulk) Save(ctx context.Context) ([]*GasPaying, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gpcb.builders))
	nodes := make([]*GasPaying, len(gpcb.builders))
	mutators := make([]Mutator, len(gpcb.builders))
	for i := range gpcb.builders {
		func(i int, root context.Context) {
			builder := gpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GasPayingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = gpcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gpcb *GasPayingCreateBulk) SaveX(ctx context.Context) []*GasPaying {
	v, err := gpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gpcb *GasPayingCreateBulk) Exec(ctx context.Context) error {
	_, err := gpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gpcb *GasPayingCreateBulk) ExecX(ctx context.Context) {
	if err := gpcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GasPaying.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GasPayingUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
//
func (gpcb *GasPayingCreateBulk) OnConflict(opts ...sql.ConflictOption) *GasPayingUpsertBulk {
	gpcb.conflict = opts
	return &GasPayingUpsertBulk{
		create: gpcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GasPaying.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (gpcb *GasPayingCreateBulk) OnConflictColumns(columns ...string) *GasPayingUpsertBulk {
	gpcb.conflict = append(gpcb.conflict, sql.ConflictColumns(columns...))
	return &GasPayingUpsertBulk{
		create: gpcb,
	}
}

// GasPayingUpsertBulk is the builder for "upsert"-ing
// a bulk of GasPaying nodes.
type GasPayingUpsertBulk struct {
	create *GasPayingCreateBulk
}

// UpdateNewValues updates the fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GasPaying.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(gaspaying.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *GasPayingUpsertBulk) UpdateNewValues() *GasPayingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(gaspaying.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GasPaying.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *GasPayingUpsertBulk) Ignore() *GasPayingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GasPayingUpsertBulk) DoNothing() *GasPayingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GasPayingCreateBulk.OnConflict
// documentation for more info.
func (u *GasPayingUpsertBulk) Update(set func(*GasPayingUpsert)) *GasPayingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GasPayingUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *GasPayingUpsertBulk) SetOrderID(v uuid.UUID) *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *GasPayingUpsertBulk) UpdateOrderID() *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdateOrderID()
	})
}

// SetPaymentID sets the "payment_id" field.
func (u *GasPayingUpsertBulk) SetPaymentID(v uuid.UUID) *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetPaymentID(v)
	})
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *GasPayingUpsertBulk) UpdatePaymentID() *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdatePaymentID()
	})
}

// SetDurationMinutes sets the "duration_minutes" field.
func (u *GasPayingUpsertBulk) SetDurationMinutes(v uint32) *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetDurationMinutes(v)
	})
}

// UpdateDurationMinutes sets the "duration_minutes" field to the value that was provided on create.
func (u *GasPayingUpsertBulk) UpdateDurationMinutes() *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdateDurationMinutes()
	})
}

// SetCreateAt sets the "create_at" field.
func (u *GasPayingUpsertBulk) SetCreateAt(v uint32) *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *GasPayingUpsertBulk) UpdateCreateAt() *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *GasPayingUpsertBulk) SetUpdateAt(v uint32) *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *GasPayingUpsertBulk) UpdateUpdateAt() *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdateUpdateAt()
	})
}

// SetDeleteAt sets the "delete_at" field.
func (u *GasPayingUpsertBulk) SetDeleteAt(v uint32) *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.SetDeleteAt(v)
	})
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *GasPayingUpsertBulk) UpdateDeleteAt() *GasPayingUpsertBulk {
	return u.Update(func(s *GasPayingUpsert) {
		s.UpdateDeleteAt()
	})
}

// Exec executes the query.
func (u *GasPayingUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GasPayingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GasPayingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GasPayingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
