apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-hashing-order
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-hashing-order
  template:
    metadata:
      labels:
        app: cloud-hashing-order
    spec:
      containers:
      - name: cloud-hashing-order
        image: uhub.service.ucloud.cn/entropypool/cloud-hashing-order:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "160Mi"
            cpu: "100m"
          limits:
            memory: "160Mi"
            cpu: "100m"

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-hashing-order
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 50040
    targetPort: 50040
  - name: grpc
    port: 50041
    targetPort: 50041
  - name: healthz
    port: 50042
    targetPort: 50042
  selector:
    app: cloud-hashing-order
