// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CanceledOrder is the predicate function for canceledorder builders.
type CanceledOrder func(*sql.Selector)

// Compensate is the predicate function for compensate builders.
type Compensate func(*sql.Selector)

// GasPaying is the predicate function for gaspaying builders.
type GasPaying func(*sql.Selector)

// GoodPaying is the predicate function for goodpaying builders.
type GoodPaying func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OutOfGas is the predicate function for outofgas builders.
type OutOfGas func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)
